name = "api"
main = "src/server/index.ts"
compatibility_date = "2023-01-16"
account_id = "def0386b8f76485768a81b77913115a1"

kv_namespaces = [
    { binding = "sessions", id = "5c59602174ea4bb29543e0a63d2fef2a" },
    { binding = "challenges", id = "fcf01b2762c84b2db20630ef1ba561f2" },
]

routes = [
    { pattern = "api.passkeys.neal.codes", custom_domain = true },
]

[[ d1_databases ]]
binding = "DB"
database_name = "passkeys_db"
database_id = "03c57541-d2cb-4c00-a172-5f65196f37f5"