name = "api"
main = "src/server/index.ts"
compatibility_date = "2023-01-16"
account_id = "43d1e8a599807a9b1924410a2441412d"

kv_namespaces = [
    { binding = "sessions", id = "7179801a4e474a2a8bcd6dcae3114b97" },
    { binding = "challenges", id = "6b85111042b14d21a5d621fc6cfc9c63" },
]

routes = [{ pattern = "api.passkeys.ggez.cc", custom_domain = true }]

[[ d1_databases ]]
binding = "DB"
database_name = "passkeys_db"
database_id = "5c34780e-c04f-4449-8c84-aa8303562bb5"
